import Foundation

enum DadJokes {
    static let all: [String] = [
        "Today's dad joke: Why don't scientists trust atoms? Because they make up everything.",
        "Today's dad joke: Why did the calendar get promoted? It had a lot of dates.",
        "Today's dad joke: I only know 25 letters of the alphabet. I don't know y.",
        "Today's dad joke: Why did the coffee file a police report? It got mugged.",
        "Today's dad joke: Why did the bicycle fall over? It was two-tired.",
        "Today's dad joke: What do you call fake spaghetti? An impasta.",
        "Today's dad joke: Why was the math book sad? It had too many problems.",
        "Today's dad joke: What do you call cheese that isn't yours? Nacho cheese.",
        "Today's dad joke: Why did the computer go to the doctor? It caught a virus.",
        "Today's dad joke: Why was the broom late? It swept in.",
        "Today's dad joke: What do you call a bear with no teeth? A gummy bear.",
        "Today's dad joke: Why did the tomato blush? It saw the salad dressing.",
        "Today's dad joke: Why don't eggs tell jokes? They might crack up.",
        "Today's dad joke: Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Today's dad joke: What kind of music do balloons hate? Pop.",
        "Today's dad joke: Why did the scarecrow win an award? He was outstanding in his field.",
        "Today's dad joke: Why did the cookie go to the hospital? It felt crummy.",
        "Today's dad joke: What do you call a sleeping bull? A bulldozer.",
        "Today's dad joke: Why are elevator jokes so good? They work on many levels.",
        "Today's dad joke: Why did the stadium get hot? All the fans left.",
        "Today's dad joke: What do you call a fish wearing a bowtie? Sofishticated.",
        "Today's dad joke: Why can't your nose be 12 inches long? Then it would be a foot.",
        "Today's dad joke: Why did the banana go to the doctor? It wasn't peeling well.",
        "Today's dad joke: What do clouds wear under their shorts? Thunderwear.",
        "Today's dad joke: Why did the picture go to jail? It was framed.",
        "Today's dad joke: Why did the belt get arrested? It held up a pair of pants.",
        "Today's dad joke: What did one wall say to the other? I'll meet you at the corner.",
        "Today's dad joke: Why did the orange stop? It ran out of juice.",
        "Today's dad joke: What do you call a factory that makes okay products? A satisfactory.",
        "Today's dad joke: Why did the music teacher need a ladder? To reach the high notes.",
        "Today's dad joke: Why did the phone wear glasses? It lost its contacts.",
        "Today's dad joke: What do you call a cow with no legs? Ground beef.",
        "Today's dad joke: Why did the student eat his homework? The teacher said it was a piece of cake.",
        "Today's dad joke: What did the ocean say to the beach? Nothing, it just waved.",
        "Today's dad joke: Why was six afraid of seven? Because seven eight nine.",
        "Today's dad joke: Why did the lamp fail school? It wasn't very bright.",
        "Today's dad joke: What do you call a dinosaur with a great vocabulary? A thesaurus.",
        "Today's dad joke: Why did the barber win the race? He knew a shortcut.",
        "Today's dad joke: Why did the clock get hungry? It went back four seconds.",
        "Today's dad joke: What do you call a pile of cats? A meowtain.",
        "Today's dad joke: Why don't skeletons fight each other? They don't have the guts.",
        "Today's dad joke: What did the zero say to the eight? Nice belt.",
        "Today's dad joke: Why did the computer sit by the window? It wanted a better view.",
        "Today's dad joke: Why was the keyboard calm? It had plenty of space.",
        "Today's dad joke: Why did the spreadsheet smile? Everything added up.",
        "Today's dad joke: Why did the project manager bring a pencil? To draw a conclusion.",
        "Today's dad joke: Why was the meeting so light? It had no agenda weight.",
        "Today's dad joke: Why did the task cross the road? To get to Done.",
        "Today's dad joke: Why did the deadline take a nap? It was exhausted from being chased.",
        "Today's dad joke: Why was the planner relaxed? It had everything under control.",
        "Morning dad joke: Why don't scientists trust atoms? Because they make up everything.",
        "Morning dad joke: Why did the calendar get promoted? It had a lot of dates.",
        "Morning dad joke: I only know 25 letters of the alphabet. I don't know y.",
        "Morning dad joke: Why did the coffee file a police report? It got mugged.",
        "Morning dad joke: Why did the bicycle fall over? It was two-tired.",
        "Morning dad joke: What do you call fake spaghetti? An impasta.",
        "Morning dad joke: Why was the math book sad? It had too many problems.",
        "Morning dad joke: What do you call cheese that isn't yours? Nacho cheese.",
        "Morning dad joke: Why did the computer go to the doctor? It caught a virus.",
        "Morning dad joke: Why was the broom late? It swept in.",
        "Morning dad joke: What do you call a bear with no teeth? A gummy bear.",
        "Morning dad joke: Why did the tomato blush? It saw the salad dressing.",
        "Morning dad joke: Why don't eggs tell jokes? They might crack up.",
        "Morning dad joke: Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Morning dad joke: What kind of music do balloons hate? Pop.",
        "Morning dad joke: Why did the scarecrow win an award? He was outstanding in his field.",
        "Morning dad joke: Why did the cookie go to the hospital? It felt crummy.",
        "Morning dad joke: What do you call a sleeping bull? A bulldozer.",
        "Morning dad joke: Why are elevator jokes so good? They work on many levels.",
        "Morning dad joke: Why did the stadium get hot? All the fans left.",
        "Morning dad joke: What do you call a fish wearing a bowtie? Sofishticated.",
        "Morning dad joke: Why can't your nose be 12 inches long? Then it would be a foot.",
        "Morning dad joke: Why did the banana go to the doctor? It wasn't peeling well.",
        "Morning dad joke: What do clouds wear under their shorts? Thunderwear.",
        "Morning dad joke: Why did the picture go to jail? It was framed.",
        "Morning dad joke: Why did the belt get arrested? It held up a pair of pants.",
        "Morning dad joke: What did one wall say to the other? I'll meet you at the corner.",
        "Morning dad joke: Why did the orange stop? It ran out of juice.",
        "Morning dad joke: What do you call a factory that makes okay products? A satisfactory.",
        "Morning dad joke: Why did the music teacher need a ladder? To reach the high notes.",
        "Morning dad joke: Why did the phone wear glasses? It lost its contacts.",
        "Morning dad joke: What do you call a cow with no legs? Ground beef.",
        "Morning dad joke: Why did the student eat his homework? The teacher said it was a piece of cake.",
        "Morning dad joke: What did the ocean say to the beach? Nothing, it just waved.",
        "Morning dad joke: Why was six afraid of seven? Because seven eight nine.",
        "Morning dad joke: Why did the lamp fail school? It wasn't very bright.",
        "Morning dad joke: What do you call a dinosaur with a great vocabulary? A thesaurus.",
        "Morning dad joke: Why did the barber win the race? He knew a shortcut.",
        "Morning dad joke: Why did the clock get hungry? It went back four seconds.",
        "Morning dad joke: What do you call a pile of cats? A meowtain.",
        "Morning dad joke: Why don't skeletons fight each other? They don't have the guts.",
        "Morning dad joke: What did the zero say to the eight? Nice belt.",
        "Morning dad joke: Why did the computer sit by the window? It wanted a better view.",
        "Morning dad joke: Why was the keyboard calm? It had plenty of space.",
        "Morning dad joke: Why did the spreadsheet smile? Everything added up.",
        "Morning dad joke: Why did the project manager bring a pencil? To draw a conclusion.",
        "Morning dad joke: Why was the meeting so light? It had no agenda weight.",
        "Morning dad joke: Why did the task cross the road? To get to Done.",
        "Morning dad joke: Why did the deadline take a nap? It was exhausted from being chased.",
        "Morning dad joke: Why was the planner relaxed? It had everything under control.",
        "CapJour dad joke: Why don't scientists trust atoms? Because they make up everything.",
        "CapJour dad joke: Why did the calendar get promoted? It had a lot of dates.",
        "CapJour dad joke: I only know 25 letters of the alphabet. I don't know y.",
        "CapJour dad joke: Why did the coffee file a police report? It got mugged.",
        "CapJour dad joke: Why did the bicycle fall over? It was two-tired.",
        "CapJour dad joke: What do you call fake spaghetti? An impasta.",
        "CapJour dad joke: Why was the math book sad? It had too many problems.",
        "CapJour dad joke: What do you call cheese that isn't yours? Nacho cheese.",
        "CapJour dad joke: Why did the computer go to the doctor? It caught a virus.",
        "CapJour dad joke: Why was the broom late? It swept in.",
        "CapJour dad joke: What do you call a bear with no teeth? A gummy bear.",
        "CapJour dad joke: Why did the tomato blush? It saw the salad dressing.",
        "CapJour dad joke: Why don't eggs tell jokes? They might crack up.",
        "CapJour dad joke: Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "CapJour dad joke: What kind of music do balloons hate? Pop.",
        "CapJour dad joke: Why did the scarecrow win an award? He was outstanding in his field.",
        "CapJour dad joke: Why did the cookie go to the hospital? It felt crummy.",
        "CapJour dad joke: What do you call a sleeping bull? A bulldozer.",
        "CapJour dad joke: Why are elevator jokes so good? They work on many levels.",
        "CapJour dad joke: Why did the stadium get hot? All the fans left.",
        "CapJour dad joke: What do you call a fish wearing a bowtie? Sofishticated.",
        "CapJour dad joke: Why can't your nose be 12 inches long? Then it would be a foot.",
        "CapJour dad joke: Why did the banana go to the doctor? It wasn't peeling well.",
        "CapJour dad joke: What do clouds wear under their shorts? Thunderwear.",
        "CapJour dad joke: Why did the picture go to jail? It was framed.",
        "CapJour dad joke: Why did the belt get arrested? It held up a pair of pants.",
        "CapJour dad joke: What did one wall say to the other? I'll meet you at the corner.",
        "CapJour dad joke: Why did the orange stop? It ran out of juice.",
        "CapJour dad joke: What do you call a factory that makes okay products? A satisfactory.",
        "CapJour dad joke: Why did the music teacher need a ladder? To reach the high notes.",
        "CapJour dad joke: Why did the phone wear glasses? It lost its contacts.",
        "CapJour dad joke: What do you call a cow with no legs? Ground beef.",
        "CapJour dad joke: Why did the student eat his homework? The teacher said it was a piece of cake.",
        "CapJour dad joke: What did the ocean say to the beach? Nothing, it just waved.",
        "CapJour dad joke: Why was six afraid of seven? Because seven eight nine.",
        "CapJour dad joke: Why did the lamp fail school? It wasn't very bright.",
        "CapJour dad joke: What do you call a dinosaur with a great vocabulary? A thesaurus.",
        "CapJour dad joke: Why did the barber win the race? He knew a shortcut.",
        "CapJour dad joke: Why did the clock get hungry? It went back four seconds.",
        "CapJour dad joke: What do you call a pile of cats? A meowtain.",
        "CapJour dad joke: Why don't skeletons fight each other? They don't have the guts.",
        "CapJour dad joke: What did the zero say to the eight? Nice belt.",
        "CapJour dad joke: Why did the computer sit by the window? It wanted a better view.",
        "CapJour dad joke: Why was the keyboard calm? It had plenty of space.",
        "CapJour dad joke: Why did the spreadsheet smile? Everything added up.",
        "CapJour dad joke: Why did the project manager bring a pencil? To draw a conclusion.",
        "CapJour dad joke: Why was the meeting so light? It had no agenda weight.",
        "CapJour dad joke: Why did the task cross the road? To get to Done.",
        "CapJour dad joke: Why did the deadline take a nap? It was exhausted from being chased.",
        "CapJour dad joke: Why was the planner relaxed? It had everything under control.",
        "A quick dad joke: Why don't scientists trust atoms? Because they make up everything.",
        "A quick dad joke: Why did the calendar get promoted? It had a lot of dates.",
        "A quick dad joke: I only know 25 letters of the alphabet. I don't know y.",
        "A quick dad joke: Why did the coffee file a police report? It got mugged.",
        "A quick dad joke: Why did the bicycle fall over? It was two-tired.",
        "A quick dad joke: What do you call fake spaghetti? An impasta.",
        "A quick dad joke: Why was the math book sad? It had too many problems.",
        "A quick dad joke: What do you call cheese that isn't yours? Nacho cheese.",
        "A quick dad joke: Why did the computer go to the doctor? It caught a virus.",
        "A quick dad joke: Why was the broom late? It swept in.",
        "A quick dad joke: What do you call a bear with no teeth? A gummy bear.",
        "A quick dad joke: Why did the tomato blush? It saw the salad dressing.",
        "A quick dad joke: Why don't eggs tell jokes? They might crack up.",
        "A quick dad joke: Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "A quick dad joke: What kind of music do balloons hate? Pop.",
        "A quick dad joke: Why did the scarecrow win an award? He was outstanding in his field.",
        "A quick dad joke: Why did the cookie go to the hospital? It felt crummy.",
        "A quick dad joke: What do you call a sleeping bull? A bulldozer.",
        "A quick dad joke: Why are elevator jokes so good? They work on many levels.",
        "A quick dad joke: Why did the stadium get hot? All the fans left.",
        "A quick dad joke: What do you call a fish wearing a bowtie? Sofishticated.",
        "A quick dad joke: Why can't your nose be 12 inches long? Then it would be a foot.",
        "A quick dad joke: Why did the banana go to the doctor? It wasn't peeling well.",
        "A quick dad joke: What do clouds wear under their shorts? Thunderwear.",
        "A quick dad joke: Why did the picture go to jail? It was framed.",
        "A quick dad joke: Why did the belt get arrested? It held up a pair of pants.",
        "A quick dad joke: What did one wall say to the other? I'll meet you at the corner.",
        "A quick dad joke: Why did the orange stop? It ran out of juice.",
        "A quick dad joke: What do you call a factory that makes okay products? A satisfactory.",
        "A quick dad joke: Why did the music teacher need a ladder? To reach the high notes.",
        "A quick dad joke: Why did the phone wear glasses? It lost its contacts.",
        "A quick dad joke: What do you call a cow with no legs? Ground beef.",
        "A quick dad joke: Why did the student eat his homework? The teacher said it was a piece of cake.",
        "A quick dad joke: What did the ocean say to the beach? Nothing, it just waved.",
        "A quick dad joke: Why was six afraid of seven? Because seven eight nine.",
        "A quick dad joke: Why did the lamp fail school? It wasn't very bright.",
        "A quick dad joke: What do you call a dinosaur with a great vocabulary? A thesaurus.",
        "A quick dad joke: Why did the barber win the race? He knew a shortcut.",
        "A quick dad joke: Why did the clock get hungry? It went back four seconds.",
        "A quick dad joke: What do you call a pile of cats? A meowtain.",
        "A quick dad joke: Why don't skeletons fight each other? They don't have the guts.",
        "A quick dad joke: What did the zero say to the eight? Nice belt.",
        "A quick dad joke: Why did the computer sit by the window? It wanted a better view.",
        "A quick dad joke: Why was the keyboard calm? It had plenty of space.",
        "A quick dad joke: Why did the spreadsheet smile? Everything added up.",
        "A quick dad joke: Why did the project manager bring a pencil? To draw a conclusion.",
        "A quick dad joke: Why was the meeting so light? It had no agenda weight.",
        "A quick dad joke: Why did the task cross the road? To get to Done.",
        "A quick dad joke: Why did the deadline take a nap? It was exhausted from being chased.",
        "A quick dad joke: Why was the planner relaxed? It had everything under control.",
        "Your daily dad joke: Why don't scientists trust atoms? Because they make up everything.",
        "Your daily dad joke: Why did the calendar get promoted? It had a lot of dates.",
        "Your daily dad joke: I only know 25 letters of the alphabet. I don't know y.",
        "Your daily dad joke: Why did the coffee file a police report? It got mugged.",
        "Your daily dad joke: Why did the bicycle fall over? It was two-tired.",
        "Your daily dad joke: What do you call fake spaghetti? An impasta.",
        "Your daily dad joke: Why was the math book sad? It had too many problems.",
        "Your daily dad joke: What do you call cheese that isn't yours? Nacho cheese.",
        "Your daily dad joke: Why did the computer go to the doctor? It caught a virus.",
        "Your daily dad joke: Why was the broom late? It swept in.",
        "Your daily dad joke: What do you call a bear with no teeth? A gummy bear.",
        "Your daily dad joke: Why did the tomato blush? It saw the salad dressing.",
        "Your daily dad joke: Why don't eggs tell jokes? They might crack up.",
        "Your daily dad joke: Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Your daily dad joke: What kind of music do balloons hate? Pop.",
        "Your daily dad joke: Why did the scarecrow win an award? He was outstanding in his field.",
        "Your daily dad joke: Why did the cookie go to the hospital? It felt crummy.",
        "Your daily dad joke: What do you call a sleeping bull? A bulldozer.",
        "Your daily dad joke: Why are elevator jokes so good? They work on many levels.",
        "Your daily dad joke: Why did the stadium get hot? All the fans left.",
        "Your daily dad joke: What do you call a fish wearing a bowtie? Sofishticated.",
        "Your daily dad joke: Why can't your nose be 12 inches long? Then it would be a foot.",
        "Your daily dad joke: Why did the banana go to the doctor? It wasn't peeling well.",
        "Your daily dad joke: What do clouds wear under their shorts? Thunderwear.",
        "Your daily dad joke: Why did the picture go to jail? It was framed.",
        "Your daily dad joke: Why did the belt get arrested? It held up a pair of pants.",
        "Your daily dad joke: What did one wall say to the other? I'll meet you at the corner.",
        "Your daily dad joke: Why did the orange stop? It ran out of juice.",
        "Your daily dad joke: What do you call a factory that makes okay products? A satisfactory.",
        "Your daily dad joke: Why did the music teacher need a ladder? To reach the high notes.",
        "Your daily dad joke: Why did the phone wear glasses? It lost its contacts.",
        "Your daily dad joke: What do you call a cow with no legs? Ground beef.",
        "Your daily dad joke: Why did the student eat his homework? The teacher said it was a piece of cake.",
        "Your daily dad joke: What did the ocean say to the beach? Nothing, it just waved.",
        "Your daily dad joke: Why was six afraid of seven? Because seven eight nine.",
        "Your daily dad joke: Why did the lamp fail school? It wasn't very bright.",
        "Your daily dad joke: What do you call a dinosaur with a great vocabulary? A thesaurus.",
        "Your daily dad joke: Why did the barber win the race? He knew a shortcut.",
        "Your daily dad joke: Why did the clock get hungry? It went back four seconds.",
        "Your daily dad joke: What do you call a pile of cats? A meowtain.",
        "Your daily dad joke: Why don't skeletons fight each other? They don't have the guts.",
        "Your daily dad joke: What did the zero say to the eight? Nice belt.",
        "Your daily dad joke: Why did the computer sit by the window? It wanted a better view.",
        "Your daily dad joke: Why was the keyboard calm? It had plenty of space.",
        "Your daily dad joke: Why did the spreadsheet smile? Everything added up.",
        "Your daily dad joke: Why did the project manager bring a pencil? To draw a conclusion.",
        "Your daily dad joke: Why was the meeting so light? It had no agenda weight.",
        "Your daily dad joke: Why did the task cross the road? To get to Done.",
        "Your daily dad joke: Why did the deadline take a nap? It was exhausted from being chased.",
        "Your daily dad joke: Why was the planner relaxed? It had everything under control.",
        "Before we begin: Why don't scientists trust atoms? Because they make up everything.",
        "Before we begin: Why did the calendar get promoted? It had a lot of dates.",
        "Before we begin: I only know 25 letters of the alphabet. I don't know y.",
        "Before we begin: Why did the coffee file a police report? It got mugged.",
        "Before we begin: Why did the bicycle fall over? It was two-tired.",
        "Before we begin: What do you call fake spaghetti? An impasta.",
        "Before we begin: Why was the math book sad? It had too many problems.",
        "Before we begin: What do you call cheese that isn't yours? Nacho cheese.",
        "Before we begin: Why did the computer go to the doctor? It caught a virus.",
        "Before we begin: Why was the broom late? It swept in.",
        "Before we begin: What do you call a bear with no teeth? A gummy bear.",
        "Before we begin: Why did the tomato blush? It saw the salad dressing.",
        "Before we begin: Why don't eggs tell jokes? They might crack up.",
        "Before we begin: Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Before we begin: What kind of music do balloons hate? Pop.",
        "Before we begin: Why did the scarecrow win an award? He was outstanding in his field.",
        "Before we begin: Why did the cookie go to the hospital? It felt crummy.",
        "Before we begin: What do you call a sleeping bull? A bulldozer.",
        "Before we begin: Why are elevator jokes so good? They work on many levels.",
        "Before we begin: Why did the stadium get hot? All the fans left.",
        "Before we begin: What do you call a fish wearing a bowtie? Sofishticated.",
        "Before we begin: Why can't your nose be 12 inches long? Then it would be a foot.",
        "Before we begin: Why did the banana go to the doctor? It wasn't peeling well.",
        "Before we begin: What do clouds wear under their shorts? Thunderwear.",
        "Before we begin: Why did the picture go to jail? It was framed.",
        "Before we begin: Why did the belt get arrested? It held up a pair of pants.",
        "Before we begin: What did one wall say to the other? I'll meet you at the corner.",
        "Before we begin: Why did the orange stop? It ran out of juice.",
        "Before we begin: What do you call a factory that makes okay products? A satisfactory.",
        "Before we begin: Why did the music teacher need a ladder? To reach the high notes.",
        "Before we begin: Why did the phone wear glasses? It lost its contacts.",
        "Before we begin: What do you call a cow with no legs? Ground beef.",
        "Before we begin: Why did the student eat his homework? The teacher said it was a piece of cake.",
        "Before we begin: What did the ocean say to the beach? Nothing, it just waved.",
        "Before we begin: Why was six afraid of seven? Because seven eight nine.",
        "Before we begin: Why did the lamp fail school? It wasn't very bright.",
        "Before we begin: What do you call a dinosaur with a great vocabulary? A thesaurus.",
        "Before we begin: Why did the barber win the race? He knew a shortcut.",
        "Before we begin: Why did the clock get hungry? It went back four seconds.",
        "Before we begin: What do you call a pile of cats? A meowtain.",
        "Before we begin: Why don't skeletons fight each other? They don't have the guts.",
        "Before we begin: What did the zero say to the eight? Nice belt.",
        "Before we begin: Why did the computer sit by the window? It wanted a better view.",
        "Before we begin: Why was the keyboard calm? It had plenty of space.",
        "Before we begin: Why did the spreadsheet smile? Everything added up.",
        "Before we begin: Why did the project manager bring a pencil? To draw a conclusion.",
        "Before we begin: Why was the meeting so light? It had no agenda weight.",
        "Before we begin: Why did the task cross the road? To get to Done.",
        "Before we begin: Why did the deadline take a nap? It was exhausted from being chased.",
        "Before we begin: Why was the planner relaxed? It had everything under control.",
        "Start-day smile: Why don't scientists trust atoms? Because they make up everything.",
        "Start-day smile: Why did the calendar get promoted? It had a lot of dates.",
        "Start-day smile: I only know 25 letters of the alphabet. I don't know y.",
        "Start-day smile: Why did the coffee file a police report? It got mugged.",
        "Start-day smile: Why did the bicycle fall over? It was two-tired.",
        "Start-day smile: What do you call fake spaghetti? An impasta.",
        "Start-day smile: Why was the math book sad? It had too many problems.",
        "Start-day smile: What do you call cheese that isn't yours? Nacho cheese.",
        "Start-day smile: Why did the computer go to the doctor? It caught a virus.",
        "Start-day smile: Why was the broom late? It swept in.",
        "Start-day smile: What do you call a bear with no teeth? A gummy bear.",
        "Start-day smile: Why did the tomato blush? It saw the salad dressing.",
        "Start-day smile: Why don't eggs tell jokes? They might crack up.",
        "Start-day smile: Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Start-day smile: What kind of music do balloons hate? Pop.",
        "Start-day smile: Why did the scarecrow win an award? He was outstanding in his field.",
        "Start-day smile: Why did the cookie go to the hospital? It felt crummy.",
        "Start-day smile: What do you call a sleeping bull? A bulldozer.",
        "Start-day smile: Why are elevator jokes so good? They work on many levels.",
        "Start-day smile: Why did the stadium get hot? All the fans left.",
        "Start-day smile: What do you call a fish wearing a bowtie? Sofishticated.",
        "Start-day smile: Why can't your nose be 12 inches long? Then it would be a foot.",
        "Start-day smile: Why did the banana go to the doctor? It wasn't peeling well.",
        "Start-day smile: What do clouds wear under their shorts? Thunderwear.",
        "Start-day smile: Why did the picture go to jail? It was framed.",
        "Start-day smile: Why did the belt get arrested? It held up a pair of pants.",
        "Start-day smile: What did one wall say to the other? I'll meet you at the corner.",
        "Start-day smile: Why did the orange stop? It ran out of juice.",
        "Start-day smile: What do you call a factory that makes okay products? A satisfactory.",
        "Start-day smile: Why did the music teacher need a ladder? To reach the high notes.",
        "Start-day smile: Why did the phone wear glasses? It lost its contacts.",
        "Start-day smile: What do you call a cow with no legs? Ground beef.",
        "Start-day smile: Why did the student eat his homework? The teacher said it was a piece of cake.",
        "Start-day smile: What did the ocean say to the beach? Nothing, it just waved.",
        "Start-day smile: Why was six afraid of seven? Because seven eight nine.",
        "Start-day smile: Why did the lamp fail school? It wasn't very bright.",
        "Start-day smile: What do you call a dinosaur with a great vocabulary? A thesaurus.",
        "Start-day smile: Why did the barber win the race? He knew a shortcut.",
        "Start-day smile: Why did the clock get hungry? It went back four seconds.",
        "Start-day smile: What do you call a pile of cats? A meowtain.",
        "Start-day smile: Why don't skeletons fight each other? They don't have the guts.",
        "Start-day smile: What did the zero say to the eight? Nice belt.",
        "Start-day smile: Why did the computer sit by the window? It wanted a better view.",
        "Start-day smile: Why was the keyboard calm? It had plenty of space.",
        "Start-day smile: Why did the spreadsheet smile? Everything added up.",
        "Start-day smile: Why did the project manager bring a pencil? To draw a conclusion.",
        "Start-day smile: Why was the meeting so light? It had no agenda weight.",
        "Start-day smile: Why did the task cross the road? To get to Done.",
        "Start-day smile: Why did the deadline take a nap? It was exhausted from being chased.",
        "Start-day smile: Why was the planner relaxed? It had everything under control.",
        "Today's tiny laugh: Why don't scientists trust atoms? Because they make up everything.",
        "Today's tiny laugh: Why did the calendar get promoted? It had a lot of dates.",
        "Today's tiny laugh: I only know 25 letters of the alphabet. I don't know y.",
        "Today's tiny laugh: Why did the coffee file a police report? It got mugged.",
        "Today's tiny laugh: Why did the bicycle fall over? It was two-tired.",
        "Today's tiny laugh: What do you call fake spaghetti? An impasta.",
        "Today's tiny laugh: Why was the math book sad? It had too many problems.",
        "Today's tiny laugh: What do you call cheese that isn't yours? Nacho cheese.",
        "Today's tiny laugh: Why did the computer go to the doctor? It caught a virus.",
        "Today's tiny laugh: Why was the broom late? It swept in.",
        "Today's tiny laugh: What do you call a bear with no teeth? A gummy bear.",
        "Today's tiny laugh: Why did the tomato blush? It saw the salad dressing.",
        "Today's tiny laugh: Why don't eggs tell jokes? They might crack up.",
        "Today's tiny laugh: Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Today's tiny laugh: What kind of music do balloons hate? Pop.",
        "Today's tiny laugh: Why did the scarecrow win an award? He was outstanding in his field.",
        "Today's tiny laugh: Why did the cookie go to the hospital? It felt crummy.",
        "Today's tiny laugh: What do you call a sleeping bull? A bulldozer.",
        "Today's tiny laugh: Why are elevator jokes so good? They work on many levels.",
        "Today's tiny laugh: Why did the stadium get hot? All the fans left.",
        "Today's tiny laugh: What do you call a fish wearing a bowtie? Sofishticated.",
        "Today's tiny laugh: Why can't your nose be 12 inches long? Then it would be a foot.",
        "Today's tiny laugh: Why did the banana go to the doctor? It wasn't peeling well.",
        "Today's tiny laugh: What do clouds wear under their shorts? Thunderwear.",
        "Today's tiny laugh: Why did the picture go to jail? It was framed.",
        "Today's tiny laugh: Why did the belt get arrested? It held up a pair of pants.",
        "Today's tiny laugh: What did one wall say to the other? I'll meet you at the corner.",
        "Today's tiny laugh: Why did the orange stop? It ran out of juice.",
        "Today's tiny laugh: What do you call a factory that makes okay products? A satisfactory.",
        "Today's tiny laugh: Why did the music teacher need a ladder? To reach the high notes.",
        "Today's tiny laugh: Why did the phone wear glasses? It lost its contacts.",
        "Today's tiny laugh: What do you call a cow with no legs? Ground beef.",
        "Today's tiny laugh: Why did the student eat his homework? The teacher said it was a piece of cake.",
        "Today's tiny laugh: What did the ocean say to the beach? Nothing, it just waved.",
        "Today's tiny laugh: Why was six afraid of seven? Because seven eight nine.",
        "Today's tiny laugh: Why did the lamp fail school? It wasn't very bright.",
        "Today's tiny laugh: What do you call a dinosaur with a great vocabulary? A thesaurus.",
        "Today's tiny laugh: Why did the barber win the race? He knew a shortcut.",
        "Today's tiny laugh: Why did the clock get hungry? It went back four seconds.",
        "Today's tiny laugh: What do you call a pile of cats? A meowtain.",
        "Today's tiny laugh: Why don't skeletons fight each other? They don't have the guts.",
        "Today's tiny laugh: What did the zero say to the eight? Nice belt.",
        "Today's tiny laugh: Why did the computer sit by the window? It wanted a better view.",
        "Today's tiny laugh: Why was the keyboard calm? It had plenty of space.",
        "Today's tiny laugh: Why did the spreadsheet smile? Everything added up.",
        "Today's tiny laugh: Why did the project manager bring a pencil? To draw a conclusion.",
        "Today's tiny laugh: Why was the meeting so light? It had no agenda weight.",
        "Today's tiny laugh: Why did the task cross the road? To get to Done.",
        "Today's tiny laugh: Why did the deadline take a nap? It was exhausted from being chased.",
        "Today's tiny laugh: Why was the planner relaxed? It had everything under control.",
        "Daily groan incoming: Why don't scientists trust atoms? Because they make up everything.",
        "Daily groan incoming: Why did the calendar get promoted? It had a lot of dates.",
        "Daily groan incoming: I only know 25 letters of the alphabet. I don't know y.",
        "Daily groan incoming: Why did the coffee file a police report? It got mugged.",
        "Daily groan incoming: Why did the bicycle fall over? It was two-tired.",
        "Daily groan incoming: What do you call fake spaghetti? An impasta.",
        "Daily groan incoming: Why was the math book sad? It had too many problems.",
        "Daily groan incoming: What do you call cheese that isn't yours? Nacho cheese.",
        "Daily groan incoming: Why did the computer go to the doctor? It caught a virus.",
        "Daily groan incoming: Why was the broom late? It swept in.",
        "Daily groan incoming: What do you call a bear with no teeth? A gummy bear.",
        "Daily groan incoming: Why did the tomato blush? It saw the salad dressing.",
        "Daily groan incoming: Why don't eggs tell jokes? They might crack up.",
        "Daily groan incoming: Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Daily groan incoming: What kind of music do balloons hate? Pop.",
        "Daily groan incoming: Why did the scarecrow win an award? He was outstanding in his field.",
        "Daily groan incoming: Why did the cookie go to the hospital? It felt crummy.",
        "Daily groan incoming: What do you call a sleeping bull? A bulldozer.",
        "Daily groan incoming: Why are elevator jokes so good? They work on many levels.",
        "Daily groan incoming: Why did the stadium get hot? All the fans left.",
        "Daily groan incoming: What do you call a fish wearing a bowtie? Sofishticated.",
        "Daily groan incoming: Why can't your nose be 12 inches long? Then it would be a foot.",
        "Daily groan incoming: Why did the banana go to the doctor? It wasn't peeling well.",
        "Daily groan incoming: What do clouds wear under their shorts? Thunderwear.",
        "Daily groan incoming: Why did the picture go to jail? It was framed.",
        "Daily groan incoming: Why did the belt get arrested? It held up a pair of pants.",
        "Daily groan incoming: What did one wall say to the other? I'll meet you at the corner.",
        "Daily groan incoming: Why did the orange stop? It ran out of juice.",
        "Daily groan incoming: What do you call a factory that makes okay products? A satisfactory.",
        "Daily groan incoming: Why did the music teacher need a ladder? To reach the high notes.",
        "Daily groan incoming: Why did the phone wear glasses? It lost its contacts.",
        "Daily groan incoming: What do you call a cow with no legs? Ground beef.",
        "Daily groan incoming: Why did the student eat his homework? The teacher said it was a piece of cake.",
        "Daily groan incoming: What did the ocean say to the beach? Nothing, it just waved.",
        "Daily groan incoming: Why was six afraid of seven? Because seven eight nine.",
        "Daily groan incoming: Why did the lamp fail school? It wasn't very bright.",
        "Daily groan incoming: What do you call a dinosaur with a great vocabulary? A thesaurus.",
        "Daily groan incoming: Why did the barber win the race? He knew a shortcut.",
        "Daily groan incoming: Why did the clock get hungry? It went back four seconds.",
        "Daily groan incoming: What do you call a pile of cats? A meowtain.",
        "Daily groan incoming: Why don't skeletons fight each other? They don't have the guts.",
        "Daily groan incoming: What did the zero say to the eight? Nice belt.",
        "Daily groan incoming: Why did the computer sit by the window? It wanted a better view.",
        "Daily groan incoming: Why was the keyboard calm? It had plenty of space.",
        "Daily groan incoming: Why did the spreadsheet smile? Everything added up.",
        "Daily groan incoming: Why did the project manager bring a pencil? To draw a conclusion.",
        "Daily groan incoming: Why was the meeting so light? It had no agenda weight.",
        "Daily groan incoming: Why did the task cross the road? To get to Done.",
        "Daily groan incoming: Why did the deadline take a nap? It was exhausted from being chased.",
        "Daily groan incoming: Why was the planner relaxed? It had everything under control.",
        "One for the day: Why don't scientists trust atoms? Because they make up everything.",
        "One for the day: Why did the calendar get promoted? It had a lot of dates.",
        "One for the day: I only know 25 letters of the alphabet. I don't know y.",
        "One for the day: Why did the coffee file a police report? It got mugged.",
        "One for the day: Why did the bicycle fall over? It was two-tired.",
        "One for the day: What do you call fake spaghetti? An impasta.",
        "One for the day: Why was the math book sad? It had too many problems.",
        "One for the day: What do you call cheese that isn't yours? Nacho cheese.",
        "One for the day: Why did the computer go to the doctor? It caught a virus.",
        "One for the day: Why was the broom late? It swept in.",
        "One for the day: What do you call a bear with no teeth? A gummy bear.",
        "One for the day: Why did the tomato blush? It saw the salad dressing.",
        "One for the day: Why don't eggs tell jokes? They might crack up.",
        "One for the day: Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "One for the day: What kind of music do balloons hate? Pop.",
        "One for the day: Why did the scarecrow win an award? He was outstanding in his field.",
        "One for the day: Why did the cookie go to the hospital? It felt crummy.",
        "One for the day: What do you call a sleeping bull? A bulldozer.",
        "One for the day: Why are elevator jokes so good? They work on many levels.",
        "One for the day: Why did the stadium get hot? All the fans left.",
        "One for the day: What do you call a fish wearing a bowtie? Sofishticated.",
        "One for the day: Why can't your nose be 12 inches long? Then it would be a foot.",
        "One for the day: Why did the banana go to the doctor? It wasn't peeling well.",
        "One for the day: What do clouds wear under their shorts? Thunderwear.",
        "One for the day: Why did the picture go to jail? It was framed.",
        "One for the day: Why did the belt get arrested? It held up a pair of pants.",
        "One for the day: What did one wall say to the other? I'll meet you at the corner.",
        "One for the day: Why did the orange stop? It ran out of juice.",
        "One for the day: What do you call a factory that makes okay products? A satisfactory.",
        "One for the day: Why did the music teacher need a ladder? To reach the high notes.",
        "One for the day: Why did the phone wear glasses? It lost its contacts.",
        "One for the day: What do you call a cow with no legs? Ground beef.",
        "One for the day: Why did the student eat his homework? The teacher said it was a piece of cake.",
        "One for the day: What did the ocean say to the beach? Nothing, it just waved.",
        "One for the day: Why was six afraid of seven? Because seven eight nine.",
        "One for the day: Why did the lamp fail school? It wasn't very bright.",
        "One for the day: What do you call a dinosaur with a great vocabulary? A thesaurus.",
        "One for the day: Why did the barber win the race? He knew a shortcut.",
        "One for the day: Why did the clock get hungry? It went back four seconds.",
        "One for the day: What do you call a pile of cats? A meowtain.",
        "One for the day: Why don't skeletons fight each other? They don't have the guts.",
        "One for the day: What did the zero say to the eight? Nice belt.",
        "One for the day: Why did the computer sit by the window? It wanted a better view.",
        "One for the day: Why was the keyboard calm? It had plenty of space.",
        "One for the day: Why did the spreadsheet smile? Everything added up.",
        "One for the day: Why did the project manager bring a pencil? To draw a conclusion.",
        "One for the day: Why was the meeting so light? It had no agenda weight.",
        "One for the day: Why did the task cross the road? To get to Done.",
        "One for the day: Why did the deadline take a nap? It was exhausted from being chased.",
        "One for the day: Why was the planner relaxed? It had everything under control."
    ]
}
