name: Alsagier
options:
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.softfm.alsagierapp
    SWIFT_VERSION: "5.0"
targets:
  Alsagier:
    type: application
    platform: iOS
    sources:
      - path: .
        includes:
          - "*.swift"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.softfm.alsagierapp
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: Alsagier.entitlements
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: Alsagier
